steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
logsBucket: 'gs://almecija-logsbucket'
images: 
- 'gcr.io/$PROJECT_ID/quickstart-image'
